import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const {PGlite}=await import(process.env.LEAD_DB_MODULE);
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls; create table organizations(id uuid primary key);create table msg_channel_accounts(id uuid primary key,organization_id uuid);create table crm_contacts(id uuid primary key,organization_id uuid);`);
await db.exec(await readFile(new URL('../migrations/20261002214655_restore_campaign_engine.sql',import.meta.url),'utf8'));
const org='11111111-1111-1111-1111-111111111111',foreign='22222222-2222-2222-2222-222222222222',account='33333333-3333-3333-3333-333333333333',contact='44444444-4444-4444-4444-444444444444',token='55555555-5555-5555-5555-555555555555';
await db.exec(`insert into organizations values('${org}'),('${foreign}');insert into msg_channel_accounts values('${account}','${org}');insert into crm_contacts values('${contact}','${org}')`);
const {rows:[tpl]}=await db.query(`insert into cmp_templates(organization_id,name,body) values($1,'t','first') returning id`,[org]);
await db.query(`update cmp_templates set body='second' where id=$1`,[tpl.id]);
assert.equal((await db.query('select count(*)::int as n from cmp_template_versions')).rows[0].n,2);
const {rows:[c]}=await db.query(`insert into cmp_campaigns(organization_id,name,channel_account_id,template_id,template_version,status)values($1,'c',$2,$3,2,'running')returning id`,[org,account,tpl.id]);
await assert.rejects(db.query(`insert into cmp_campaigns(organization_id,name,channel_account_id,template_id,template_version) values($1,'foreign',$2,$3,2)`,[foreign,account,tpl.id]));
await db.query(`insert into cmp_recipients(organization_id,campaign_id,contact_id,phone)values($1,$2,$3,'905000000000')`,[org,c.id,contact]);
assert.equal((await db.query(`select cmp_claim_campaign($1,$2,$3) as ok`,[c.id,foreign,token])).rows[0].ok,false);
assert.equal((await db.query(`select cmp_claim_campaign($1,$2,$3) as ok`,[c.id,org,token])).rows[0].ok,true);
assert.equal((await db.query(`select cmp_claim_campaign($1,$2,$3) as ok`,[c.id,org,account])).rows[0].ok,false);
assert.equal((await db.query(`select * from cmp_claim_recipients($1,$2,$3,20)`,[c.id,org,token])).rows.length,1);
assert.equal((await db.query(`select * from cmp_claim_recipients($1,$2,$3,20)`,[c.id,org,token])).rows.length,0);
await db.query(`update cmp_recipients set status='read' where campaign_id=$1`,[c.id]);
assert.deepEqual((await db.query('select stats from cmp_campaigns where id=$1',[c.id])).rows[0].stats,{total:1,queued:0,sending:0,sent:1,delivered:1,read:1,failed:0,skipped:0});
assert.equal((await db.query(`select has_table_privilege('anon','cmp_campaigns','select') as ok`)).rows[0].ok,false);
assert.equal((await db.query(`select has_function_privilege('authenticated','cmp_claim_campaign(uuid,uuid,uuid)','execute') as ok`)).rows[0].ok,false);
console.log('Campaign PostgreSQL: snapshots, tenant FK, exclusive lease, one-time claims, cumulative stats and server-only permissions passed');
await db.close();
