begin;
do $$
declare o uuid; other_o uuid; cost uuid; foreign_cost uuid; p uuid; v uuid; batch uuid; buyer uuid; ord uuid; item uuid; failed boolean;
begin
 insert into organizations(name,slug) values('Price test','price-test-'||gen_random_uuid()) returning id into o;
 insert into organizations(name,slug) values('Other price test','other-price-test-'||gen_random_uuid()) returning id into other_o;
 insert into sales_product_attributes(organization_id,name,kind,scope,is_price_floor) values(o,'سعر التصنيع','money','product',true) returning id into cost;
 insert into sales_product_attributes(organization_id,name,kind,scope,is_price_floor) values(other_o,'تكلفة أخرى','money','product',true) returning id into foreign_cost;
 insert into sales_products(organization_id,name,price,attributes) values(o,'Price test',10000,jsonb_build_object(cost::text,1000)) returning id into p;
 if sales_price_floor(o,jsonb_build_object(cost::text,1000))<>1000 then raise exception 'Named floor not read'; end if;
 failed:=false;
 begin update sales_products set attributes=jsonb_build_object(foreign_cost::text,500) where id=p; exception when others then failed:=true; end;
 if not failed then raise exception 'Cross-org field accepted'; end if;
 failed:=false;
 begin update sales_products set price=999 where id=p; exception when others then failed:=true; end;
 if not failed then raise exception 'Base price below cost accepted'; end if;
 insert into sales_product_variants(organization_id,product_id,label) values(o,p,'أساسي') returning id into v;
 batch:=create_sales_stock_batch(o,p,v,'TEST',null,20,null);
 insert into crm_contacts(organization_id,full_name) values(o,'Price buyer') returning id into buyer;
 insert into sales_orders(organization_id,contact_id,total) values(o,buyer,5000) returning id into ord;
 failed:=false;
 begin insert into sales_order_items(organization_id,order_id,product_id,batch_id,product_name,quantity,list_unit_price,sold_unit_price,line_total) values(o,ord,p,batch,'Test',1,10000,999,999); exception when others then failed:=true; end;
 if not failed then raise exception 'Sale below floor accepted'; end if;
 failed:=false;
 begin insert into sales_order_items(organization_id,order_id,product_id,batch_id,product_name,quantity,list_unit_price,sold_unit_price,line_total) values(o,ord,p,batch,'Test',1,10000,10001,10001); exception when others then failed:=true; end;
 if not failed then raise exception 'Sale above list price accepted'; end if;
 insert into sales_order_items(organization_id,order_id,product_id,batch_id,product_name,quantity,list_unit_price,sold_unit_price,line_total) values(o,ord,p,batch,'Test',1,10000,5000,5000) returning id into item;
 if (select minimum_unit_price from sales_order_items where id=item)<>1000 then raise exception 'Floor snapshot not captured'; end if;
 update sales_products set attributes=jsonb_build_object(cost::text,6000) where id=p;
 failed:=false;
 begin perform confirm_sales_order(o,ord,null); exception when others then failed:=true; end;
 if not failed or (select quantity from sales_stock_batches where id=batch)<>20 or (select status from sales_orders where id=ord)<>'draft' then raise exception 'Cost increase did not block confirmation atomically'; end if;
 update sales_order_items set sold_unit_price=7000,line_total=7000 where id=item;
 update sales_orders set total=7000 where id=ord;
 perform confirm_sales_order(o,ord,null);
 if (select quantity from sales_stock_batches where id=batch)<>19 then raise exception 'Valid discounted sale failed'; end if;
 if has_function_privilege('authenticated','public.sales_price_floor(uuid,jsonb)','execute') or has_function_privilege('anon','public.validate_sales_line_price()','execute') then raise exception 'Price helpers exposed'; end if;
end $$;
select 'Named cost, price boundaries, snapshots, changed cost, atomic stock, tenant isolation: PASS' as result;
rollback;
